// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CURE.Domain.Entities;

public partial class BookingStatusHistory
{
    public long Id { get; set; }

    public long BookingId { get; set; }

    public int? OldStatusId { get; set; }

    public int NewStatusId { get; set; }

    public long ChangedByUserId { get; set; }

    public DateTime ChangedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Users ChangedByUser { get; set; }

    public virtual BookingStatus NewStatus { get; set; }

    public virtual BookingStatus OldStatus { get; set; }
}