// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CURE.Domain.Entities;

public partial class BookingStatus
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<BookingStatusHistory> BookingStatusHistoryNewStatuses { get; set; } = new List<BookingStatusHistory>();

    public virtual ICollection<BookingStatusHistory> BookingStatusHistoryOldStatuses { get; set; } = new List<BookingStatusHistory>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}