// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CURE.Domain.Entities;

public partial class Booking
{
    public long Id { get; set; }

    public long PatientId { get; set; }

    public long NurseId { get; set; }

    public DateTime AppointmentDate { get; set; }

    public int BookingStatusId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual BookingStatus BookingStatus { get; set; }

    public virtual ICollection<BookingStatusHistory> BookingStatusHistories { get; set; } = new List<BookingStatusHistory>();

    public virtual Nurse Nurse { get; set; }

    public virtual Patient Patient { get; set; }
}