// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CURE.Domain.Entities;

public partial class ClinicalNote
{
    public long Id { get; set; }

    public long PatientId { get; set; }

    public long NurseId { get; set; }

    public string Note { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Nurse Nurse { get; set; }

    public virtual Patient Patient { get; set; }
}