// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CURE.Domain.Entities;

public partial class Nurse
{
    public long Id { get; set; }

    public long UserId { get; set; }

    public string Specialization { get; set; }

    public string LicenseNumber { get; set; }

    public int YearsOfExperience { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime? DeletedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<ClinicalNote> ClinicalNotes { get; set; } = new List<ClinicalNote>();

    public virtual Users User { get; set; }
}