// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CURE.Domain.Entities;

public partial class PatientFile
{
    public long Id { get; set; }

    public long PatientId { get; set; }

    public string FileName { get; set; }

    public string FileType { get; set; }

    public string FilePath { get; set; }

    public DateTime UploadedAt { get; set; }

    public virtual Patient Patient { get; set; }
}